controller:
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
    internal:
      enabled: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      ports:
        http: 443
        https: 80
      targetPorts:
        http: 443
        https: 80
