controller:
  service:
    type: ClusterIP
  containerSecurityContext:
    allowPrivilegeEscalation: false
  extraModules:
    - name: opentelemetry
      image:
        registry: registry.k8s.io
        image: busybox
        tag: latest
