controller:
  service:
    type: ClusterIP
  extraModules:
    - name: opentelemetry
      image:
        registry: registry.k8s.io
        image: busybox
        tag: latest
      containerSecurityContext:
        allowPrivilegeEscalation: false
